# Generated by Django 4.0.1 on 2022-09-13 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, default="payment", max_length=30),
                ),
                (
                    "receive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving",
                        to="bal.fiatwallet",
                    ),
                ),
                (
                    "send",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending",
                        to="bal.fiatwallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositTrans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bal.compayuser"
                    ),
                ),
            ],
        ),
    ]
